apiVersion: apps/v1
kind: Deployment
metadata:
  name: ng-events-frontend-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: { app: ng-events-frontend }
  template:
    metadata:
      labels: { app: ng-events-frontend }
    spec:
      containers:
        - name: ng-events-frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
          resources:
            requests: { cpu: "100m", memory: "128Mi" }
            limits:   { cpu: "500m", memory: "512Mi" }